library iconsax;

import 'package:flutter/widgets.dart';

class Iconsax {
  const Iconsax._();

  static const String _fontFamily = 'iconsax';
  static const String _kFontPkg = 'iconsax';



  static const IconData shopping_bag =
      IconData(0xe977, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData shopping_cart =
      IconData(0xe978, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData bag_2 =
      IconData(0xe979, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData shop =
      IconData(0xe97a, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData chart_3 =
      IconData(0xe962, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData flag =
      IconData(0xe963, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData message_question =
      IconData(0xe964, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData radar_1 =
      IconData(0xe965, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData gas_station =
      IconData(0xe966, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData delete =
      IconData(0xe967, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData undo =
      IconData(0xe968, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData circle =
      IconData(0xe969, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData panorama_fisheye =
      IconData(0xe96a, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData link =
      IconData(0xe96b, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData chevron_down =
      IconData(0xe96c, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData horizontal_rotate_clockwise =
      IconData(0xe96d, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData format_quote_close =
      IconData(0xe96e, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData code_json =
      IconData(0xe96f, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData format_list_numbered =
      IconData(0xe970, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData format_strikethrough =
      IconData(0xe971, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData format_underline =
      IconData(0xe972, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData format_italic =
      IconData(0xe973, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData format_bold =
      IconData(0xe974, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData edit_2 =
      IconData(0xe975, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData volume_mute =
      IconData(0xe976, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData global =
      IconData(0xe961, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData discount_shape =
      IconData(0xe981, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData people =
      IconData(0xe982, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData dollar_square =
      IconData(0xe983, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData usd_coin_usdc =
      IconData(0xe984, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData calendar_1 =
      IconData(0xe980, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData trustwallet =
      IconData(0xe95f, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData metamask_logo =
      IconData(0xe960, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData walletconnect =
      IconData(0xe97e, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData uniqueswap =
      IconData(0xe97f, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData wldlp_1 =
      IconData(0xe95d, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData wldlp_2 =
      IconData(0xe95e, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData trustmonk =
      IconData(0xe95a, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData nftmonk =
      IconData(0xe95b, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData documonk =
      IconData(0xe95c, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData heart_filled =
      IconData(0xe959, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData Indian_Rupee_symbol =
      IconData(0xe958, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData nft_collection_13042 =
      IconData(0xe93f, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData nft_hand_13049 =
      IconData(0xe940, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData nft_store_13048 =
      IconData(0xe941, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData nft_token_13059 =
      IconData(0xe942, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData nft_investment_13053 =
      IconData(0xe943, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData nft_token_13046 =
      IconData(0xe944, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData nft_wallet_13050 =
      IconData(0xe945, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData nft_blockchain_13054 =
      IconData(0xe946, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData nft_license_13043 =
      IconData(0xe947, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData nft_buy_sell_13038 =
      IconData(0xe948, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData nft_auction_13051_1 =
      IconData(0xe949, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData category_2 =
      IconData(0xe94a, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData arrowline_up_3 =
      IconData(0xe94b, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData arrowline_down_1 =
      IconData(0xe94c, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData arrowline_right_1 =
      IconData(0xe94d, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData arrowline_left =
      IconData(0xe94e, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData bookmark_2 =
      IconData(0xe94f, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData box_1 =
      IconData(0xe950, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData profile_tick =
      IconData(0xe951, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData bank =
     IconData(0xe952, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData ipfs =
      IconData(0xe953, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData dcube =
      IconData(0xe954, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData trush_square =
      IconData(0xe955, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData trash =
      IconData(0xe956, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData delete_circle =
      IconData(0xe957, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData icon =
      IconData(0xe900, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData call =
      IconData(0xe901, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData empty_wallet =
      IconData(0xe902, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData cloud_off_outline =
      IconData(0xe903, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData dots_horizontal =
      IconData(0xe904, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData dots_vertical =
      IconData(0xe905, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData format_list_bulleted =
      IconData(0xe906, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData google_chrome =
      IconData(0xe907, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData whatsapp =
      IconData(0xe908, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData instagram =
      IconData(0xe909, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData linkedin =
      IconData(0xe90a, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData twitter =
      IconData(0xe90b, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData facebook =
      IconData(0xe90c, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData star_1 =
      IconData(0xe90d, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData star =
      IconData(0xe90e, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData tools =
      IconData(0xe90f, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData scanner =
      IconData(0xe910, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData scan =
      IconData(0xe911, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData check =
      IconData(0xe912, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData warning_2 =
      IconData(0xe913, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData unlock =
      IconData(0xe914, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData heart =
      IconData(0xe915, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData document_1 =
      IconData(0xe916, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData document_upload =
      IconData(0xe917, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData copy_success =
      IconData(0xe918, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData copy =
      IconData(0xe919, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData security_safe =
      IconData(0xe91a, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData profile_circle =
      IconData(0xe91b, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData warning_21 =
      IconData(0xe91c, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData arrow_down =
      IconData(0xe91d, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData arrow_up_1 =
      IconData(0xe91e, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData info_circle =
      IconData(0xe91f, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData refresh =
      IconData(0xe920, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData add =
      IconData(0xe921, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData more =
      IconData(0xe922, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData close_circle =
      IconData(0xe923, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData arrow_down_1 =
      IconData(0xe924, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData arrow_left_2 =
      IconData(0xe925, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData arrow_right_3 =
      IconData(0xe926, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData arrow_up_2 =
      IconData(0xe927, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData arrow_circle_down =
      IconData(0xe928, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData arrow_circle_left =
      IconData(0xe929, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData arrow_circle_right =
      IconData(0xe92a, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData arrow_circle_up =
      IconData(0xe92b, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData directbox_send =
      IconData(0xe92c, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData ethereum_classic_etc =
      IconData(0xe92d, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData polygon_matic =
      IconData(0xe92e, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData tick_circle =
      IconData(0xe92f, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData money_send =
      IconData(0xe930, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData clock =
      IconData(0xe931, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData card =
      IconData(0xe932, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData card_pos =
      IconData(0xe933, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData folder_add =
      IconData(0xe934, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData setting =
      IconData(0xe935, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData timer =
      IconData(0xe936, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData search_normal_1 =
      IconData(0xe937, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xe938, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData chart_2 =
      IconData(0xe939, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData chart_21 =
      IconData(0xe93a, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData element_2 =
      IconData(0xe93b, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData notification =
      IconData(0xe93c, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData menu_1 =
      IconData(0xe93d, fontFamily: _fontFamily, fontPackage: _kFontPkg);
  static const IconData empty_wallet1 =
      IconData(0xe93e, fontFamily: _fontFamily, fontPackage: _kFontPkg);
}
